### PR TITLE
Update

### PR DESCRIPTION
**Pull request by DavesarXKhushal**

### CODE REVIEW

**Comment by kavinvalli** [comment]
Hmmm ya I'm not sure this will work cause of how we're deploying the repository. Take a look at the this
https://github.com/New-Delhi-Space-Society/new-delhi-space-society.github.io/blob/3760c2ac4414b0fddf377e4a68e19b7802daef5c/README.md?plain=1#L25

**Comment by kavinvalli** [comment]
actually, i think i might be wrong cause we upgraded the nextjs version which fixed this. I'll try merging cause anyways it's not working and this shouldn't break more than what is already broken 🤷

**Comment by DavesarXKhushal** [comment]
Like what I deployed was working at my server. What's the issue right here ?

**Comment by kavinvalli** [comment]
@DavesarXKhushal Yup my bad, it was working. Good work on your first PR! I will contact you with updates on more work soon \:)

**Comment by DavesarXKhushal** [comment]
Thankyou Bhaiya

**Pull request merged**
